spring.application.name=familytree

spring.datasource.url=gateway01.ap-southeast-1.prod.aws.tidbcloud.com
spring.datasource.username=3ij3fNrVM9VtKEq.root
spring.datasource.password=MPILuuolBNugof94

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=4000